/* 2021/04/28 
통계교육원_데이터 분석을 위한 SQL 입문_SELECT 명령으로 데이터 조회하기
*/

/* 데이터 조회하기 */
SELECT * FROM DEPARTMENTS;

SELECT DEPARTMENT_ID, LOCATION_ID
FROM DEPARTMENTS;

/* 컬럼 별칭 사용 */
SELECT DEPARTMENT_ID AS 부서ID, LOCATION_ID AS 지역ID
FROM DEPARTMENTS;

/* 중복 값 제거 */
SELECT DISTINCT LOCATION_ID
FROM DEPARTMENTS;

/* 연결 연산자 사용 */
SELECT DEPARTMENT_ID, DEPARTMENT_NAME || LOCATION_ID
FROM DEPARTMENTS;

SELECT DEPARTMENT_ID, DEPARTMENT_NAME || ' TEAM'
FROM DEPARTMENTS;

/* 실습 1) JOBS 테이블 데이터 출력  */
SELECT * FROM JOBS;

/* 실습 2) JOBS 테이블에서 JOB_TITLE, MAX_SALARY 필드 데이터 출력 */
SELECT JOB_TITLE, MAX_SALARY
FROM JOBS;

/* 실습 3) JOBS 테이블에서 JOB_ID를 ID, JOB_TITLE을 직급, MAX_SALARY를 최대급여, MIN_SALARY를 최소급여로 출력 */
SELECT JOB_ID AS ID, 
       JOB_TITLE AS 직급, 
       MAX_SALARY AS 최대급여,
       MIN_SALARY AS 최소급여
FROM JOBS;

/* 실습 4) JOB_HISTORY 테이블에서 DEPARTMENT_ID의 중복 값 없이 데이터 출력 */
SELECT DISTINCT DEPARTMENT_ID
FROM JOB_HISTORY;

/* 실습 5) LOCATIONS 테이블에서 LOCATION_ID, STATE_PROVINCE와 COUNTRY_ID는 붙여서 데이터 출력 */
SELECT LOCATION_ID, STATE_PROVINCE||COUNTRY_ID
FROM LOCATIONS;