/* 2021/04/30
통계교육원_데이터 분석을 위한 SQL 입문_집계(통계)함수 활용
*/

/* 그룹 함수 
SUM: 열의 합계 (NULL값 제외)
AVG: 열의 평균 (NULL값 제외)
MAX: 열의 최댓값
MIN: 열의 최솟값
COUNT: 열의 행 개수 (NULL값 제외)
*/
SELECT SUM(MAX_SALARY)
FROM JOBS;

SELECT SUM(MAX_SALARY),
       SUM(DISTINCT MAX_SALARY) /* 중복 값 제거 */
FROM JOBS;

SELECT AVG(MAX_SALARY)
FROM JOBS;

SELECT AVG(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID=50;

SELECT MAX(MAX_SALARY)
FROM JOBS;

SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE MANAGER_ID>=150;

SELECT MIN(MAX_SALARY) AS 최솟값
FROM JOBS;

SELECT MIN(SALARY) 최솟값
FROM EMPLOYEES
WHERE MANAGER_ID BETWEEN 100 AND 150;

/* NULL 제외 */
SELECT COUNT(COMMISSION_PCT) 개수
FROM EMPLOYEES;

/* NULL 포함 */
SELECT COUNT(NVL(COMMISSION_PCT,1)) 개수
FROM EMPLOYEES;

/* 실습 1) EMPLOYEES 테이블에서 EMPLOYEE_ID가 151에서 200사이인 COMMISSION_PCT 평균 데이터 출력(NULL값은 0으로 설정하여 포함) */
SELECT AVG(COMMISSION_PCT),
       AVG(NVL(COMMISSION_PCT, 0))
FROM EMPLOYEES
WHERE EMPLOYEE_ID BETWEEN 151 AND 200;

/* 실습 2) EMPLOYEES 테이블에서 HIRE_DATE가 가장 최근인 데이터 출력 */
SELECT MAX(HIRE_DATE)
FROM EMPLOYEES;

/* 실습 3) EMPLOYEES 테이블 행 개수 출력 */
SELECT COUNT(*)
FROM EMPLOYEES;