/* 2021/05/01
통계교육원_데이터 분석을 위한 SQL 입문_다양한 테이블의 데이터 활용(조인)
*/

/* 조인
동등 조인(내부 조인): 두 개 이상의 테이블에서 동일한 데이터를 찾아내는 방법
외부 조인: 테이블 간 연결하는 필드의 내용이 똑같지 않을 경우 사용, 데이터가 더 많은 쪽을 연결함(+는 데이터가 부족한 쪽에 기술)
셀프 조인: 자신의 테이블을 하나 더 복제하여 원하는 데이터를 출력할 때 사용(내용은 같지만 다른 형태의 데이터 출력 가능)
*/

SELECT *
FROM JOBS A, JOB_HISTORY B
WHERE A.JOB_ID = B.JOB_ID; 

SELECT A.JOB_ID, B.EMPLOYEE_ID, C.EMPLOYEE_ID, C.SALARY, C.FIRST_NAME
FROM JOBS A, JOB_HISTORY B, EMPLOYEES C
WHERE A.JOB_ID = B.JOB_ID
      AND B.EMPLOYEE_ID = C.EMPLOYEE_ID;

/* 외부 조인 
WHERE B.DEPARTMENT_ID = A.DEPARTMENT_ID(+) 왼쪽 외부 조인
WHERE B.DEPARTMENT_ID(+) = A.DEPARTMENT_ID 오른쪽 외부 조인
*/    
SELECT B.FIRST_NAME, B.DEPARTMENT_ID, A.DEPARTMENT_ID, A.DEPARTMENT_NAME
FROM DEPARTMENTS A, EMPLOYEES B
WHERE B.DEPARTMENT_ID = A.DEPARTMENT_ID(+);


/* 실습 1) LOCATIONS, COUNTRIES 테이블에서 COUNTRY_ID가 동일한 데이터만 출력 */
SELECT A.LOCATION_ID, A.CITY, B.COUNTRY_ID, B.COUNTRY_NAME
FROM LOCATIONS A, COUNTRIES B
WHERE A.COUNTRY_ID = B.COUNTRY_ID;

/* 실습 2) LOCATIONS, COUNTRIES 테이블에서 COUNTRY_ID가 동일한 LOCATIONS 모든 데이터 출력 */
SELECT A.LOCATION_ID, A.CITY, B.COUNTRY_ID, B.COUNTRY_NAME
FROM LOCATIONS A, COUNTRIES B
WHERE A.COUNTRY_ID(+) = B.COUNTRY_ID;

/* 실습 3) LOCATIONS 테이블을 이용하여 CITY,의 COUNTRY_ID 출력(자체 조인) */
SELECT A.CITY, B.COUNTRY_ID
FROM LOCATIONS A, LOCATIONS B
WHERE A.COUNTRY_ID = B.COUNTRY_ID;