/* 2021/05/03
통계교육원_데이터 분석을 위한 SQL 입문_데이터 저장 객체 관리
*/

/* DDL: 데이터의 정의(커밋없이 자동 저장)        cf)DML: 데이터의 조작(커밋하여 반영)
행=튜플=레코드, 열=속성=필드
CREATE TABLE: 새로운 테이블 생성
ALTER ADD/MODIFY/RENAME(COLUMN) ~ TO/DROP COLUMN : 테이블 추가/수정/이름 변경(열 이름 변경)/열 삭제
TRUNCATE: 테이블의 데이터를 모두 삭제할 때 사용(구조는 그대로 남음)
DROP: 테이블 완전 삭제(구조도 삭제됨)
*/

CREATE TABLE MOSAIC
(MOSAIC_ID NUMBER,
MOSAIC_NAME VARCHAR2(20),
EMAIL VARCHAR2(20)
);

/* 생성된 테이블 확인 */ 
SELECT *
FROM MOSAIC;

INSERT INTO MOSAIC VALUES(1, 'KIM', 'KIM@MOSAICIT.COM');

ALTER TABLE MOSAIC 
ADD (TEL VARCHAR2(13));

ALTER TABLE MOSAIC
MODIFY (MOSAIC_NAME CHAR(15));

ALTER TABLE MOSAIC
RENAME COLUMN TEL TO PHONE;

ALTER TABLE MOSAIC
DROP COLUMN PHONE;

TRUNCATE TABLE MOSAIC;

DROP TABLE MOSAIC;

/* 실습 1) SHOP_ID는 NUMBER, ITEM은 VARCHAR1(30), PRICE는 NUMBER 형식의 SHOPPING 테이블 생성 */
CREATE TABLE SHOPPING
(SHOP_ID NUMBER, 
ITEM VARCHAR2(30),
PRICE NUMBER
);

SELECT * 
FROM SHOPPING;

/* 실습 2) SHOPPING 테이블에 필드명이 ADDR, 타입이 VARCHAR2(200)인 필드를 삽입 */
ALTER TABLE SHOPPING
ADD(ADDR VARCHAR2(200));

/* 실습 3) SHOPPING 테이블 삭제 */
DROP TABLE SHOPPING;